### ISSUE TITLE
BRS classification on external dataset

### ISSUE THREAD

**Issue by biototem** [CostelloLab/BRSpred#1]
Hi, thanks for this wonderful work！It is mentioned in the manuscript that the BRS classifier was applied to external datasets such as TCGA BLCA. Is it possible to share the BRS classification results for the TCGA BLCA cohort? Thanks!

**Comment by Syksy** [comment]
Hello @biototem ,

terribly sorry for the late reply to the issue ticket. For some reason I didn't get a ping.

For the exact code reproducing the TCGA BLCA results, I'll contact the colleague of mine who ran that part of the R code. I'll try get back to you with this.

However, should you feel inclined to already test it around with the current R-package, I can highly recommend [curatedTCGAData](https://bioconductor.org/packages/release/data/experiment/html/curatedTCGAData.html) from Bioconductor for processing the TCGA BLCA for `BRS` compatible format.

For example with:
```
library(curatedTCGAData)
blca_tcga <- curatedTCGAData(
	diseaseCode = "BLCA", assays = "*", version = "2.0.1"
)

> blca_tcga[grep("RNASeq", blca_tcga$title),]
    ah_id                         title file_size           rdataclass rdatadateadded rdatadateremoved
9  EH4762    BLCA_miRNASeqGene-20160128    0.3 Mb SummarizedExperiment     2021-01-27             <NA>
11 EH4764     BLCA_RNASeq2Gene-20160128   14.7 Mb SummarizedExperiment     2021-01-27             <NA>
12 EH4765 BLCA_RNASeq2GeneNorm-20160128   21.9 Mb SummarizedExperiment     2021-01-27             <NA>
13 EH4766      BLCA_RNASeqGene-20160128    2.4 Mb               DFrame     2021-01-27             <NA>
```

... and then proceeding with processing it into an expression matrix with HUGO symbols on rows and samples of interest as columns, which would be the desired input for the `BRS` function.

Please note that the following instructions could be followed (quoting from the Materials and Methods in the paper, mainly referencing the `DESeq2` R-package after manual download from GDC): 

"The TCGA BLCA dataset was downloaded using the Genomic Data Commons portal (via https://portal.gdc.cancer.gov/projects/TCGA-BLCA). For both datasets, raw counts were variance-stabilizing transformation (VST)–normalized using DESeq2 and then used for downstream analyses."

**Comment by biototem** [comment]
Thank you for your reply!
We aimed to validate the BRS subtype's ability to predict BCG efficacy using two local NMIBC cohorts. Initially, we planned to train a deep learning model to predict BRS using H&E images from the TCGA BLCA cohort, as we lack sequencing data for our cohorts. However, we recently realized that most samples in TCGA are MIBC, potentially making them unsuitable for NMIBC prediction.
Incidentally, we came across your conference abstract proposing a similar idea of using H&E images to predict BRS. We look forward to your upcoming publications for more details on this approach and see if there is any opportunity for collaboration!

**Comment by fcdejong** [comment]
Dear biototem, 

Thank you for your interest and sorry for the delay in response. As for you question, we suggest you use the BRSpred package on the TCGA dataset. In this way, you will get the exact results u need. There might be a small discrepancy between your results and those presented in the paper, based on two things: the input TCGA dataset you are using, and the fact we ran an original _pamr_ object to get results. But I'm absolutely sure it will be highly similar. 

Of note, predicting BRS using HE slides from MIBC patients makes no sense to me at all. These are vastly different samples, different cohorts and MIIBC samples contain a lot of muscle-invasive tissue. These are much more aggressive too. 

If your interested in collaborating, we should have a meeting (f.c.dejong@erasmusmc.nl). We also have a PhD candidate working on a similar DL project!

Best!

Chris

**Comment by Syksy** [comment]
I believe Chris above answered the question regarding the TCGA portion, so I'll close this issue as it's not directly connected to the BRSpred package's current state per se.
